import { useEffect, useState } from 'react';
import type React from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { registerSW } from 'virtual:pwa-register';
import './style.css';

type Summary = { id: string; title: string; coverUrl: string | null; latestChapter?: string };
type ChapterSummary = { id: string; mangaId: string; title: string };
type Details = Summary & { description: string; chapters: ChapterSummary[] };
type Chapter = { id: string; mangaId: string; title: string; pages: { index: number; imageUrl: string }[]; previousChapterId?: string; nextChapterId?: string };
type History = { mangaId: string; mangaTitle: string; chapterId: string; chapterTitle: string; position: number; timestamp: number };
const api = async <T,>(path: string): Promise<T> => { const r = await fetch(`/api${path}`); if (!r.ok) throw new Error((await r.json().catch(() => null))?.error ?? 'Request failed'); return r.json(); };
const covers = (items: Summary[]) => <div className="grid">{items.map(m => <Link className="cover" key={m.id} to={`/manga/${encodeURIComponent(m.id)}`}><div className="cover-image">{m.coverUrl ? <img src={m.coverUrl} alt="" loading="lazy" /> : 'Y'}</div><b>{m.title}</b>{m.latestChapter && <small>{m.latestChapter}</small>}</Link>)}</div>;
function Shell({ children }: { children: React.ReactNode }) { const loc = useLocation(); const reader = loc.pathname.includes('/reader/'); return <><main className={reader ? 'reader-page' : 'app'}>{children}</main>{!reader && <nav className="bottom"><Link to="/" className={loc.pathname === '/' ? 'active' : ''}>Home</Link><Link to="/search" className={loc.pathname === '/search' ? 'active' : ''}>Search</Link></nav>}</>; }
function Home() { const [latest, setLatest] = useState<Summary[]>([]); const [error, setError] = useState(''); const [history, setHistory] = useState<History[]>([]); useEffect(() => { api<Summary[]>('/latest').then(setLatest).catch(e => setError(e.message)); setHistory(JSON.parse(localStorage.getItem('yomi-history') ?? '[]')); }, []); return <Shell><header><h1>Yomi</h1><span>Olympus reader</span></header>{history.length > 0 && <section><div className="section-title"><h2>Continue Reading</h2><button onClick={() => { localStorage.removeItem('yomi-history'); setHistory([]); }}>Clear</button></div><div className="continue">{history.slice(0, 4).map(h => <Link key={`${h.mangaId}-${h.chapterId}`} to={`/reader/${encodeURIComponent(h.mangaId)}/${encodeURIComponent(h.chapterId)}`}>{h.mangaTitle}<small>{h.chapterTitle}</small></Link>)}</div></section>}<section><h2>Latest</h2>{error ? <p className="error">{error}</p> : latest.length ? covers(latest) : <p>Loading latest releases…</p>}</section></Shell>; }
function Search() { const [q, setQ] = useState(''); const [results, setResults] = useState<Summary[]>([]); const [status, setStatus] = useState(''); const submit = async (e: React.FormEvent) => { e.preventDefault(); if (!q.trim()) return setStatus('Enter a title to search.'); setStatus('Searching…'); try { setResults(await api(`/search?q=${encodeURIComponent(q.trim())}`)); setStatus(''); } catch (err) { setStatus(err instanceof Error ? err.message : 'Search failed'); } }; return <Shell><header><h1>Search</h1></header><form className="search" onSubmit={submit}><input value={q} onChange={e => setQ(e.target.value)} placeholder="Search Olympus" aria-label="Search Olympus" /><button>Search</button></form>{status && <p>{status}</p>}{!status && results.length > 0 && covers(results)}{!status && q && results.length === 0 && <p>No results yet.</p>}</Shell>; }
function Manga() { const { mangaId = '' } = useParams(); const [manga, setManga] = useState<Details | null>(null); const [error, setError] = useState(''); useEffect(() => { api<Details>(`/manga/${encodeURIComponent(mangaId)}`).then(setManga).catch(e => setError(e.message)); }, [mangaId]); if (error) return <Shell><p className="error">{error}</p></Shell>; if (!manga) return <Shell><p>Loading manga…</p></Shell>; return <Shell><Link className="back" to="/">← Home</Link><article className="details"><div className="detail-cover">{manga.coverUrl && <img src={manga.coverUrl} alt="" />}</div><div><h1>{manga.title}</h1><p>{manga.description || 'No description available.'}</p></div></article><section><h2>Chapters</h2><div className="chapters">{manga.chapters.map(c => <Link key={c.id} to={`/reader/${encodeURIComponent(manga.id)}/${encodeURIComponent(c.id)}`}>{c.title}<span>Read →</span></Link>)}</div></section></Shell>; }
function Reader() { const { mangaId = '', chapterId = '' } = useParams(); const nav = useNavigate(); const [chapter, setChapter] = useState<Chapter | null>(null); const [error, setError] = useState(''); useEffect(() => { api<Chapter>(`/manga/${encodeURIComponent(mangaId)}/chapter/${encodeURIComponent(chapterId)}`).then(setChapter).catch(e => setError(e.message)); }, [mangaId, chapterId]); useEffect(() => { if (!chapter) return; const saved = (JSON.parse(localStorage.getItem('yomi-history') ?? '[]') as History[]).find(h => h.mangaId === mangaId && h.chapterId === chapterId); if (saved?.position) setTimeout(() => window.scrollTo(0, saved.position), 200); let timer = 0; const save = () => { window.clearTimeout(timer); timer = window.setTimeout(() => { const all = JSON.parse(localStorage.getItem('yomi-history') ?? '[]') as History[]; const next = [{ mangaId, mangaTitle: mangaId.replace(/-/g, ' '), chapterId, chapterTitle: chapter.title, position: window.scrollY, timestamp: Date.now() }, ...all.filter(h => !(h.mangaId === mangaId && h.chapterId === chapterId))].slice(0, 20); localStorage.setItem('yomi-history', JSON.stringify(next)); }, 400); }; window.addEventListener('scroll', save, { passive: true }); return () => { window.removeEventListener('scroll', save); window.clearTimeout(timer); }; }, [chapter, mangaId, chapterId]); if (error) return <Shell><p className="error">{error}</p></Shell>; if (!chapter) return <Shell><p>Loading chapter…</p></Shell>; return <Shell><div className="reader-top"><button onClick={() => nav(`/manga/${encodeURIComponent(mangaId)}`)}>← Back</button><span>{chapter.title}</span></div><div className="pages">{chapter.pages.map(p => <img key={p.index} src={p.imageUrl} loading="lazy" alt={`Page ${p.index + 1}`} />)}</div><div className="reader-next">{chapter.previousChapterId && <Link to={`/reader/${encodeURIComponent(mangaId)}/${encodeURIComponent(chapter.previousChapterId)}`}>Previous</Link>}{chapter.nextChapterId && <Link to={`/reader/${encodeURIComponent(mangaId)}/${encodeURIComponent(chapter.nextChapterId)}`}>Next</Link>}</div></Shell>; }
function App() { return <Routes><Route path="/" element={<Home />} /><Route path="/search" element={<Search />} /><Route path="/manga/:mangaId" element={<Manga />} /><Route path="/reader/:mangaId/:chapterId" element={<Reader />} /></Routes>; }
registerSW({ immediate: true }); createRoot(document.getElementById('root')!).render(<BrowserRouter><App /></BrowserRouter>);
