import * as cheerio from 'cheerio';
import type { Chapter, ChapterSummary, MangaDetails, MangaSource, MangaSummary } from './models.js';

const BASE = 'https://olympustaff.com';
const agent = 'Yomi personal reader/0.1 (+local development; public content only)';
export class SourceError extends Error { constructor(message: string, public status = 502) { super(message); } }
const text = (value: string | undefined) => (value ?? '').replace(/\s+/g, ' ').trim();
const slug = (href: string | undefined, prefix = '/series/') => { try { const parts = new URL(href ?? '', BASE).pathname.split('/').filter(Boolean); const at = parts.indexOf(prefix.replaceAll('/', '')); return at >= 0 ? parts[at + 1] ?? '' : ''; } catch { return ''; } };
const chapterId = (href: string | undefined) => { try { const p = new URL(href ?? '', BASE).pathname.split('/').filter(Boolean); return p.at(-1) ?? ''; } catch { return ''; } };
export function parseSearch(html: string): MangaSummary[] { const $ = cheerio.load(html); return $('a[href*="/series/"]').map((_, el) => { const a = $(el); const id = slug(a.attr('href')); const title = text(a.find('h1,h2,h3,h4').first().text()) || text(a.find('img').attr('alt')); const coverUrl = a.find('img').first().attr('src') ?? null; return id && title ? { id, title, coverUrl: absolute(coverUrl) } : null; }).get().filter((x): x is MangaSummary => x !== null); }
export function parseLatest(html: string): MangaSummary[] { const $ = cheerio.load(html); const seen = new Set<string>(); const out: MangaSummary[] = []; $('.last-chapter .box, .last-chapter article').each((_, el) => { const root = $(el); const links = root.find('a[href*="/series/"]'); const manga = links.filter((_, a) => new URL($(a).attr('href') ?? '', BASE).pathname.split('/').filter(Boolean).length === 2).first(); const id = slug(manga.attr('href')); const title = text(manga.text()) || text(root.find('h3,h2').first().text()); if (!id || !title || seen.has(id)) return; seen.add(id); const latest = text(links.last().text()); out.push({ id, title, coverUrl: absolute(root.find('img').first().attr('src') ?? null), latestChapter: latest || undefined }); }); return out; }
export function parseChapterList(html: string, id: string): ChapterSummary[] { const $ = cheerio.load(html); const chapters: ChapterSummary[] = []; const seen = new Set<string>(); $('#chaptersContainer .chapter-link[href], a.chapter-link[href]').each((_, el) => { const a = $(el); const href = a.attr('href'); const chapter = chapterId(href); if (!chapter || chapter === id || seen.has(chapter) || !href?.includes(`/series/${id}/`)) return; seen.add(chapter); chapters.push({ id: chapter, mangaId: id, title: text(a.find('.chapter-number,.chapter-title').text()) || text(a.text()) || `Chapter ${chapter}` }); }); return chapters; }
export function parseManga(html: string, id: string): MangaDetails { const $ = cheerio.load(html); const title = text($('h1').filter((_, el) => text($(el).text()).length > 1).first().text()) || text($('title').text()).split('-')[0]; const coverUrl = absolute($('meta[property="og:image"]').attr('content') ?? $('.manga-image img, .summary_image img, img[alt*="Manga"]').first().attr('src') ?? null); const description = text($('.summary__content, .description, .manga-description, .post-content').first().text()); const chapters = parseChapterList(html, id); if (!title || chapters.length === 0) throw new SourceError('Manga was not found or has no publicly available chapters.', 404); return { id, title, coverUrl, description, chapters }; }
export function parseChapter(html: string, mangaId: string, id: string): Chapter { const $ = cheerio.load(html); const pages = $('.image_list img.manga-chapter-img').map((index, el) => absolute($(el).attr('src') ?? null) ? { index, imageUrl: absolute($(el).attr('src') ?? '')! } : null).get().filter((x): x is { index: number; imageUrl: string } => x !== null); if (!pages.length) throw new SourceError('Chapter was not found or is not publicly accessible.', 404); const previous = chapterId($('#prev-chapter[href]').attr('href')); const next = chapterId($('#next-chapter[href]').attr('href')); return { id, mangaId, title: text($('#chapter-heading').text()) || `Chapter ${id}`, pages, previousChapterId: previous || undefined, nextChapterId: next || undefined }; }
const absolute = (url: string | null) => { if (!url) return null; try { const resolved = new URL(url, BASE); return resolved.protocol === 'https:' && resolved.hostname === 'olympustaff.com' ? resolved.href : null; } catch { return null; } };
export class OlympusSource implements MangaSource {
  async getLatest() { return parseLatest(await this.fetch('/')); }
  async search(query: string) { return parseSearch(await this.fetch(`/ajax/search?keyword=${encodeURIComponent(query)}`, { 'X-Requested-With': 'XMLHttpRequest' })); }
  async getManga(id: string) { const first = await this.fetch(`/series/${encodeURIComponent(id)}`); const manga = parseManga(first, id); const $ = cheerio.load(first); const pageCount = Math.min(10, Math.max(1, ...$('.pagination a[href*="page="]').map((_, el) => Number(new URL($(el).attr('href') ?? '', BASE).searchParams.get('page')) || 1).get())); if (pageCount > 1) { const rest = await Promise.all(Array.from({ length: pageCount - 1 }, (_, i) => this.fetch(`/series/${encodeURIComponent(id)}?page=${i + 2}`))); const seen = new Set(manga.chapters.map(chapter => chapter.id)); for (const html of rest) for (const chapter of parseChapterList(html, id)) if (!seen.has(chapter.id)) { seen.add(chapter.id); manga.chapters.push(chapter); } } return manga; }
  async getChapter(mangaId: string, id: string) { return parseChapter(await this.fetch(`/series/${encodeURIComponent(mangaId)}/${encodeURIComponent(id)}`), mangaId, id); }
  private async fetch(path: string, extraHeaders: Record<string, string> = {}) { try { const response = await fetch(`${BASE}${path}`, { headers: { 'User-Agent': agent, ...extraHeaders }, signal: AbortSignal.timeout(12_000) }); if (response.status === 404) throw new SourceError('Content was not found.', 404); if (!response.ok) throw new SourceError('Olympus is currently unavailable.', 502); return await response.text(); } catch (error) { if (error instanceof SourceError) throw error; throw new SourceError('Could not reach Olympus.'); } }
}
